
##############################
# Country definition for USA #
##############################

province =
{ id       = 1486
  air_base = { size = 4 current_size = 4 }
}            # Kabul

province =
{ id         = 761
  naval_base = { size = 10 current_size = 10 }
}              # San Diego

province =
{ id         = 780
  naval_base = { size = 5 current_size = 5 }
}              # Seattle

province =
{ id         = 1624
  naval_base = { size = 2 current_size = 2 }
    air_base = { size = 8 current_size = 8 }
}              # Guam

province =
{ id         = 663
  naval_base = { size = 8 current_size = 8 }
    air_base = { size = 8 current_size = 8 }
}              # Pearl Harbour

province =
{ id         = 633
  naval_base = { size = 10 current_size = 10 }
}              # Norfolk

province =
{ id         = 600
  naval_base = { size = 5 current_size = 5 }
}              # Boston

province =
{ id         = 648
  naval_base = { size = 5 current_size = 5 }
}              # Jacksonville

province =
{ id         = 1614
  naval_base = { size = 10 current_size = 10 }
    air_base = { size = 10 current_size = 10 }
  supplypool = 5000
  oilpool    = 2000
}              # Kuweit

province =
{ id         = 651
    air_base = { size = 10 current_size = 10 }
}            # Miami

province =
{ id         = 595
    air_base = { size = 10 current_size = 10 }
}            # Concord

province =
{ id         = 621
    air_base = { size = 8 current_size = 8 }
}            # Milwaukee

province =
{ id         = 722
    air_base = { size = 10 current_size = 10 }
}            # Roswell

province =
{ id         = 766
    air_base = { size = 10 current_size = 10 }
}            # Redding

province =
{ id         = 765
 rocket_test = { size = 4 current_size = 4 }
}            # San Fransisco

province =
{ id         = 726
      nuclear_reactor = 9
}            # Los Alamos

province =
{ id         = 1193
  naval_base = { size = 8 current_size = 8 }
    air_base = { size = 8 current_size = 8 }
}              # Okinawa


country =
{ tag                 = USA
  # Resource Reserves
  nuke                = 180
  energy              = 10000
  metal               = 8000
  rare_materials      = 5000
  oil                 = 10000
  supplies            = 8000
  money               = 500
  manpower            = 160
  transports          = 1000
  escorts             = 50
  capital             = 606
  diplomacy =
  { relation =
    { tag        = CAN
      value      = 200
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation = { tag = MEX value = 50 }
    relation = { tag = CUB value = -100 }
    relation =
    { tag        = PAN
      value      = 100
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation = { tag = COL value = 150 access = yes }
    relation = { tag = VEN value = -50 }
    relation = { tag = BRA value = 100 }
    relation = { tag = CHL value = 50 }
    relation = { tag = ARG value = 50 }
    relation =
    { tag        = ICL
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = DEN
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = NOR
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation = { tag = SWE value = 150 }
    relation = { tag = FIN value = 150 }
    relation =
    { tag        = EST
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = LAT
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = LIT
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation = { tag = BLR value = -100 }
    relation = { tag = UKR value = -50 }
    relation =
    { tag        = POL
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = GER
      value      = 100
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = FRA
      value      = 100
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = HOL
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = BEL
      value      = 100
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = ENG
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = IRE
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = SPA
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = POR
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = CZE
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = SLO
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = AUS
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = HUN
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = ITA
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = ROM
      value      = 100
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = BUL
      value      = 90
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = GRE
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = TUR
      value      = 100
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = SLV
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation = { tag = CRO value = 50 }
    relation = { tag = SER value = -20 }
    relation = { tag = CYN value = 150 access = yes }
    relation = { tag = BOS value = 50 access = yes }
    relation = { tag = GEO value = 150 access = yes }
    relation = { tag = U18 value = 150 access = yes }
    relation = { tag = RSI value = 150 access = yes }
    relation = { tag = AZB value = 150 }
    relation = { tag = SYR value = -150 }
    relation = { tag = PER value = -150 }
    relation = { tag = IRQ value = -200 }
    relation =
    { tag        = SAU
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = OMN
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = U14
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = QUE
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation = { tag = EUS value = -150 }
    relation = { tag = KAZ value = 50 }
    relation = { tag = UZB value = 100 access = yes }
    relation =
    { tag        = KYG
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation = { tag = TAJ value = 150 access = yes }
    relation = { tag = TRK value = -20 access = yes }
    relation = { tag = PAK value = 90 access = yes }
    relation = { tag = IND value = 100 }
    relation = { tag = CHC value = 50 }
    relation = { tag = U09 value = -170 }
    relation =
    { tag        = KOR
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = JAP
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = TRA
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation = { tag = BUR value = -150 }
    relation =
    { tag        = PHI
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = NZL
      value      = 150
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation =
    { tag        = AST
      value      = 200
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
    relation = { tag = HON value = 50 access = yes }
    relation = { tag = MOR value = 50 access = yes }
    relation = { tag = EGY value = 70 access = yes }
    relation = { tag = SIA value = 70 }
    relation = { tag = U06 value = 120 }
    relation = { tag = INO value = 70 }
    relation =
    { tag        = ISR
      value      = 170
      access     = yes
      guaranteed = { day = 22 month = march year = 1003 }
    }
}
  SpyInfo                = { country = "CHC" NumberOfSpies = 4 }
  SpyInfo                = { country = "U09" NumberOfSpies = 2 }
  SpyInfo                = { country = "JAP" NumberOfSpies = 2 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 3 }
  SpyInfo                = { country = "VEN" NumberOfSpies = 5 }
  SpyInfo                = { country = "MEX" NumberOfSpies = 5 }
  SpyInfo                = { country = "BRA" NumberOfSpies = 3 }
  SpyInfo                = { country = "BLR" NumberOfSpies = 3 }
  SpyInfo                = { country = "RUS" NumberOfSpies = 4 }
  SpyInfo                = { country = "IND" NumberOfSpies = 2 }
  SpyInfo                = { country = "PAK" NumberOfSpies = 3 }
  SpyInfo                = { country = "PER" NumberOfSpies = 4 }
  SpyInfo                = { country = "IRQ" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 2 }
  SpyInfo                = { country = "GUA" NumberOfSpies = 5 }
  SpyInfo                = { country = "CUB" NumberOfSpies = 4 }
  SpyInfo                = { country = "COL" NumberOfSpies = 3 }
  SpyInfo                = { country = "ARG" NumberOfSpies = 2 }
  SpyInfo                = { country = "BUR" NumberOfSpies = 1 }
  SpyInfo                = { country = "EGY" NumberOfSpies = 2 }
  SpyInfo                = { country = "UZB" NumberOfSpies = 3 }
  SpyInfo                = { country = "GEO" NumberOfSpies = 4 }
  SpyInfo                = { country = "UKR" NumberOfSpies = 4 }
  SpyInfo                = { country = "KAZ" NumberOfSpies = 2 }
  SpyInfo                = { country = "ISR" NumberOfSpies = 3 }
  SpyInfo                = { country = "SAU" NumberOfSpies = 2 }
  SpyInfo                = { country = "CAN" NumberOfSpies = 1 }
  SpyInfo                = { country = "KYG" NumberOfSpies = 2 }
  nationalprovinces   = { 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606  607 
                          605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614  629  630 
                          640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685  686  687  688 
                          689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789  790  791  792  793 
                          710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730  731  732  733  706  707 
                          708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781  782  783  784  785  786  778 
                          769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547  546  545  544  543  542  718  726 
                          746  895  658  659  660  661  662  663  1766 1786 1624 1408 1764 1765 1625 1626 1627 1604 1609 1610 1612 1613 1615 1616 1617
                          1618 1619 1620
                        }
  ownedprovinces      = { 1614 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606  607 
                          605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614  629  630 
                          640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685  686  687  688 
                          689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789  790  791  792  793 
                          710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730  731  732  733  706  707 
                          708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781  782  783  784  785  786  778 
                          769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547  546  545  544  543  542  718  726 
                          746  895  658  659  660  661  662  663  1766 1786 1624 1408 1764 1765 1625 1626 1627 1604 1609 1610 1612 1613 1615 1616 1617
                          1618 1619 1620 1193 1486 1493 1492 1484
                        }
  controlledprovinces = { 1614 651  650  649  648  677  676  672  646  647  669  670  644  645  634  635  636  637  643  633  632  631  638  639  606  607 
                          605  604  603  612  602  598  593  592  608  609  610  611  594  597  595  596  582  583  599  600  601  613  614  629  630 
                          640  641  642  671  673  674  675  678  679  615  628  617  616  618  619  627  680  681  682  683  684  685  686  687  688 
                          689  626  625  620  621  624  623  622  690  691  692  693  694  695  696  697  698  699  787  788  789  790  791  792  793 
                          710  711  712  713  714  715  716  717  719  720  721  748  722  723  724  725  727  728  729  730  731  732  733  706  707 
                          708  709  705  704  703  702  701  700  775  774  770  771  772  773  776  777  779  780  781  782  783  784  785  786  778 
                          769  768  734  736  735  767  761  762  763  764  765  766  553  551  550  549  548  547  546  545  544  543  542  718  726 
                          746  895  658  659  660  661  662  663  1766 1786 1624 1408 1764 1765 1625 1626 1627 1604 1609 1610 1612 1613 1615 1616 1617
                          1618 1619 1620 1193 1486 1493 1492 1484
                        }
  techapps            = {
					#Industry
					5010 5020 5030 5040 5050 5060 5070 5080 5090
					5110 5120 5130 5140 5150 5160 5170 5180 5190
					5210 5220 5230 5240 5250 5260 5270 5280 5290
					#Army Equip
					2200 2210 2220 2230
					2300 2310 2320 2330
					2400 2410 2420 2420
					2500 2510 2520 2530
					2600 2610 2620 2630
					2700 2710 2720 2730
					2800 2810 2820 2830
					2000 2010 2050
					2110 2120
					#Army Org
					1980 1970
					1260 1270
					1900 1910 1920 1930
					1500 1510 1520 1530
					1400 1410 1420 1430
					1300 1310 1320 1330
					1200 1210 1220 1230
					1600 1650
					1610 1660
					1800 1810 1820
					1700 1710 1720
					1000 1010
					1110 1120
					#Aircraft
					4800 4810 4820
					4700 4710 4720
					4750 4760 4770
					4000 4010 4020 4030
					4100 4110 4120 4130
                                        4640 4650 4660 4670
					4600 4610 4620
					4550 4570
					4500 4510 4520
					4200 4210 4220
					4900 4910 4920
					4400 4410 4420
					4300 4310 4320
					#Land Docs
					6930
					6010 6030 6050 6070 6080
					6600 6630
					6700 6730
					6100 6110 6120 6130 6140 6150 6160 6170	
					6200 6210 6220 6230 6240 6250 6260 6270
					6300 6310 6320 6330 6340 6350 6360 6370
					#Air Docs
					9040 9510 9520 9530 9540
					9050 9060 9070 9080 9090 9100 9110 9120
					9130 9140 9150 9160 9170 9180 9190 9200
					9210 9220 9230 9240 9250 9260 9270 9280
					9450 9460 9470
					#Secret Weapons
					7010
					7020 7030 7040 7050
					7060 7070 7080
					7180 7190 7200 7210
					7240
                                        7330 7310 7320
					7270 7280 7290 7300
					7140
					7240 7250 7260
					7100 7110 7120
                                        #Navy
                                        3000 3010 3020
                                        3100 3110 3120 3130
                                        3200 3210 3220
                                        3300 3310 3320
                                        3590 3600 3610 3620
                                        3800 3810 38810 3820 38820 3830
                                        3850 3860 3870 3880
                                        3900 3910 3920
                                        #Navy Doctrines
                                        8900 8910 8920 8930
                                        8950 8960 8970 8980
                                        8400 8410 8420
                                        8000 8010 8020
                                        8500 8510 8520
                                        8100 8110 8120 8130
                                        8600 8610 8620 8630
                                        8200 8210 8220
                                        8700 8710 8720
                                        8300 8310 8320 8330
                                        8800 8810 8820 8830
					
                        }
  blueprints = { 4040 4140 7150 7340 }
  policy =
  { date              = { year = 0 month = march day = 0 }
    democratic        = 10
    political_left    = 2
    free_market       = 8
    freedom           = 8
    professional_army = 6
    defense_lobby     = 5
    interventionism   = 9
  }
  # #####################################
  # ARMY
  # #####################################
  landunit =
  { id       = { type = 22400 id = 1 }
    location = 634
    name     = "XVIII Airborne Corps"
    division =
    { id            = { type = 22400 id = 2 }
      name          = "11th Armored Cavalry Regiment"
      strength      = 100
      type          = light_armor
      model         = 7
      extra         = heavy_armor
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 22400 id = 3 }
    location = 1614
    name     = "SETAF"
    division =
    { id       = { type = 22400 id = 4 }
      name     = "173rd Airborne Brigade"
      strength = 100
      type     = paratrooper
      model    = 16
    }
  }
  landunit =
  { id       = { type = 22400 id = 5 }
    location = 549
    name     = "US Army Alaska"
    division =
    { id       = { type = 22400 id = 6 }
      name     = "172nd Infantry Brigade"
      strength = 100
      type     = mechanized
      model    = 3
    }
  }
  landunit =
  { id       = { type = 22400 id = 7 }
    location = 1199
    name     = "8th US Army"
    division =
    { id       = { type = 22400 id = 8 }
      name     = "8th US Army"
      strength = 100
      type     = hq
      model    = 2
      extra         = sp_rct_artillery
      brigade_model = 3
    }
    division =
    { id            = { type = 22400 id = 9 }
      name          = "2nd Infantry Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = heavy_armor
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 22400 id = 10 }
    location = 314
    name     = "US Forces Europe"
    division =
    { id       = { type = 22400 id = 11 }
      name     = "EUCOM"
      strength = 100
      type     = hq
      model    = 2
      extra         = sp_rct_artillery
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 22400 id = 12 }
    location = 663
    name     = "US Forces Pacific"
    division =
    { id       = { type = 22400 id = 13 }
      name     = "PACOM"
      strength = 100
      type     = hq
      model    = 2
      extra         = sp_rct_artillery
      brigade_model = 3
    }
    division =
    { id            = { type = 22400 id = 14 }
      name          = "25th Tropic Lightning Division"
      strength      = 100
      type          = infantry
      model         = 3
    }    
  }
  landunit =
  { id       = { type = 22400 id = 16 }
    location = 651
    name     = "US Forces South"
    division =
    { id       = { type = 22400 id = 17 }
      name     = "SOUTHCOM"
      strength = 100
      type     = hq
      model    = 2
      extra         = sp_rct_artillery
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 22400 id = 18 }
    location = 680
    name     = "IV Marine Expeditionary Force"
    division =
    { id            = { type = 22400 id = 19 }
      name          = "4th Marine Division"
      strength      = 100
      type          = marine
      model         = 16
      extra         = heavy_armor
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 20 }
    location = 1193
    name     = "III Marine Expeditionary Force"
    division =
    { id            = { type = 22400 id = 21 }
      name          = "3rd Marine Division"
      strength      = 100
      type          = marine
      model         = 17
      extra         = heavy_armor
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 22 }
    location = 1614
    name     = "US 3rd Army"
    division =
    { id       = { type = 22400 id = 23 }
      name     = "CENTCOM"
      strength = 100
      type     = hq
      model    = 2
    }
    division =
    { id            = { type = 22400 id = 24 }
      name          = "3rd Armored Cavalry Regiment"
      strength      = 100
      type          = light_armor
      model         = 8
    }
    division =
    { id            = { type = 22400 id = 25 }
      name          = "2nd Armored Cavalry Regiment"
      strength      = 100
      type          = light_armor
      model         = 8
    }
    division =
    { id            = { type = 22400 id = 26 }
      name          = "3rd Infantry Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = heavy_armor
      brigade_model = 3
    }
    division =
    { id            = { type = 22400 id = 27 }
      name          = "4th Infantry Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = heavy_armor
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 22400 id = 28 }
    location = 1614
    name     = "101st Airborne Division"
    division =
    { id            = { type = 22400 id = 29 }
      name          = "1st Brigade - 101st Airborne Division"
      strength      = 100
      type          = militia
      model         = 3
    }
    division =
    { id            = { type = 22400 id = 30 }
      name          = "2nd Brigade - 101st Airborne Division"
      strength      = 100
      type          = militia
      model         = 3
    }
    division =
    { id            = { type = 22400 id = 31 }
      name          = "3rd Brigade - 101st Airborne Division"
      strength      = 100
      type          = militia
      model         = 3
    }
  }
  landunit =
  { id       = { type = 22400 id = 32 }
    location = 715
    name     = "US III.Corps"
    division =
    { id            = { type = 22400 id = 33 }
      name          = "1st Cavalry Division"
      strength      = 100
      type          = armor
      model         = 16
      extra         = heavy_armor
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 22400 id = 34 }
    location = 83
    name     = "US V.Corps"
    division =
    { id            = { type = 22400 id = 35 }
      name          = "1st Armored Division"
      strength      = 100
      type          = armor
      model         = 16
      extra         = heavy_armor
      brigade_model = 2
    }
    division =
    { id            = { type = 22400 id = 36 }
      name          = "1st Infantry Division"
      strength      = 100
      type          = infantry
      model         = 3
      extra         = heavy_armor
      brigade_model = 3
    }
  }
  landunit =
  { id       = { type = 22400 id = 37 }
    location = 1614
    name     = "I Marine Expeditionary Force"
    division =
    { id            = { type = 22400 id = 38 }
      name          = "1st Marine Division"
      strength      = 100
      type          = marine
      model         = 17
      extra         = heavy_armor
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 22400 id = 39 }
    location = 1614
    name     = "II Marine Expeditionary Force"
    division =
    { id            = { type = 22400 id = 40 }
      name          = "2nd Marine Division"
      strength      = 100
      type          = marine
      model         = 17
      extra         = heavy_armor
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 41 }
    location = 1486
    name     = "10th Mountain Infantry Division"
    division =
    { id            = { type = 22400 id = 42 }
      name          = "1st Brigade - 10th Mtn Division"
      strength      = 100
      type          = bergsjaeger
      model         = 14
      extra         = police
      brigade_model = 0
    }
    division =
    { id            = { type = 22400 id = 43 }
      name          = "2nd Brigade - 10th Mtn Division"
      strength      = 100
      type          = bergsjaeger
      model         = 14
      extra         = police
      brigade_model = 0
    }
    division =
    { id            = { type = 22400 id = 44 }
      name          = "3rd Brigade - 10th Mtn Division"
      strength      = 100
      type          = bergsjaeger
      model         = 14
      extra         = police
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 22400 id = 45 }
    location = 1493
    name     = "Task Force Devil"
    division =
    { id            = { type = 22400 id = 46 }
      name          = "504th Para Inf Regiment"
      strength      = 100
      type          = militia
      model         = 3
    }
 }
  landunit =
  { id       = { type = 22400 id = 47 }
    location = 634
    name     = "Camp X"
    division =
    { id            = { type = 22400 id = 48 }
      name          = "505th Para Inf Regiment"
      strength      = 100
      type          = militia
      model         = 3
    }
 }
  # ##################################
  # US ARMY NATIONAL GUARD
  # ##################################
  landunit =
  { id       = { type = 22400 id = 88 }
    location = 707
    name     = "Colorado National Guard"
    division =
    { id       = { type = 22400 id = 49 }
      name     = "7th Infantry Division"
      strength = 30
      type     = infantry
      model    = 2
      extra         = heavy_armor
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 50 }
    location = 690
    name     = "Kansas National Guard"
    division =
    { id            = { type = 22400 id = 51 }
      name          = "35th Infantry Division"
      strength      = 30
      type          = infantry
      model         = 2
      extra         = heavy_armor
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 22400 id = 52 }
    location = 614
    name     = "Pennsylvania National Guard"
    division =
    { id            = { type = 22400 id = 53 }
      name          = "28th Infantry Division"
      strength      = 50
      type          = infantry
      model         = 2
      extra         = heavy_armor
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 54 }
    location = 632
    name     = "Virginia National Guard"
    division =
    { id            = { type = 22400 id = 55 }
      name          = "29th Infantry Division"
      strength      = 50
      type          = infantry
      model         = 2
      extra         = heavy_armor
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 56 }
    location = 693
    name     = "Minnesota National Guard"
    division =
    { id            = { type = 22400 id = 57 }
      name          = "34th Infantry Division"
      strength      = 30
      type          = infantry
      model         = 2
      extra         = heavy_armor
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 22400 id = 58 }
    location = 715
    name     = "Texas National Guard"
    division =
    { id            = { type = 22400 id = 59 }
      name          = "49th Armored Division"
      strength      = 30
      type          = armor
      model         = 15
      extra         = heavy_armor
      brigade_model = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 60 }
    location = 619
    name     = "Indianapolis National Guard"
    division =
    { id            = { type = 22400 id = 61 }
      name          = "38th Infantry Division"
      strength      = 30
      type          = infantry
      model         = 2
      extra         = heavy_armor
      brigade_model = 1
    }
    division =
    { id            = { type = 22400 id = 62 }
      name          = "76th Infantry Brigade"
      strength      = 60
      type          = cavalry
      model         = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 63 }
    location = 762
    name     = "Californa National Guard"
    division =
    { id            = { type = 22400 id = 64 }
      name          = "40th Infantry Division"
      strength      = 30
      type          = infantry
      model         = 2
      extra         = heavy_armor
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 22400 id = 65 }
    location = 602
    name     = "New York National Guard"
    division =
    { id            = { type = 22400 id = 67 }
      name          = "42th Infantry Division"
      strength      = 50
      type          = infantry
      model         = 2
      extra         = heavy_armor
      brigade_model = 2
    }
    division =
    { id            = { type = 22400 id = 68 }
      name          = "27th Infantry Brigade"
      strength      = 60
      type          = cavalry
      model         = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 69 }
    location = 663
    name     = "Hawaii National Guard"
    division =
    { id       = { type = 22400 id = 70 }
      name     = "29th Infantry Brigade"
      strength = 90
      type     = cavalry
      model    = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 71 }
    location = 636
    name     = "North Carolina National Guard"
    division =
    { id            = { type = 22400 id = 72 }
      name          = "30th Heavy Infantry Brigade"
      strength      = 90
      type          = cavalry
      model         = 2
    }
  }
  landunit =
  { id       = { type = 22400 id = 73 }
    location = 628
    name     = "South Carolina National Guard"
    division =
    { id            = { type = 22400 id = 74 }
      name          = "218th Heavy Infantry Brigade"
      strength      = 100
      type          = cavalry
      model         = 2
    }
  }
  landunit =
  { id       = { type = 22400 id = 75 }
    location = 780
    name     = "Washington National Guard"
    division =
    { id       = { type = 22400 id = 76 }
      name     = "81st Armor Brigade"
      strength = 100
      type     = light_armor
      model    = 8
    }
  }
  landunit =
  { id       = { type = 22400 id = 77 }
    location = 771
    name     = "Idaho National Guard"
    division =
    { id       = { type = 22400 id = 78 }
      name     = "116th Armor Brigade"
      strength = 60
      type     = light_armor
      model    = 7
    }
  }
  landunit =
  { id       = { type = 22400 id = 79 }
    location = 678
    name     = "Mississippi National Guard"
    division =
    { id       = { type = 22400 id = 80 }
      name     = "155th Armor Brigade"
      strength = 60
      type     = light_armor
      model    = 7
    }
  }
  landunit =
  { id       = { type = 22400 id = 81 }
    location = 621
    name     = "Winsconsin National Guard"
    division =
    { id       = { type = 22400 id = 82 }
      name     = "32nd Infantry Brigade"
      strength = 60
      type     = cavalry
      model    = 1
    }
  }
  landunit =
  { id       = { type = 22400 id = 83 }
    location = 680
    name     = "Louisiana National Guard"
    division =
    { id       = { type = 22400 id = 84 }
      name     = "256th Heavy Infantry Brigade"
      strength = 90
      type     = cavalry
      model    = 2
    }
  }
  landunit =
  { id       = { type = 22400 id = 85 }
    location = 651
    name     = "Florida National Guard"
    division =
    { id       = { type = 22400 id = 86 }
      name     = "53rd Heavy Infantry Brigade"
      strength = 90
      type     = cavalry
      model    = 2
    }
  }
  landunit =
  { id       = { type = 22400 id = 87 }
    location = 646
    name     = "Georgia National Guard"
    division =
    { id       = { type = 22400 id = 89 }
      name     = "48th Heavy Infantry Brigade"
      strength = 90
      type     = cavalry
      model    = 2
    }
  }
  landunit =
  { id       = { type = 22400 id = 90 }
    location = 1614
    name     = "SOCOM"
    division =
    { experience    = 15
      id            = { type = 22400 id = 91 }
      name          = "1st Special Operations Group"
      strength      = 100
      type          = bergsjaeger
      model         = 14
      extra         = engineer
      brigade_model = 0
    }
    division =
    { experience    = 15
      id            = { type = 22400 id = 92 }
      name          = "3rd Special Operations Group"
      strength      = 100
      type          = bergsjaeger
      model         = 14
      extra         = engineer
      brigade_model = 0
    }
    division =
    { experience    = 15
      id            = { type = 22400 id = 93 }
      name          = "5th Special Operations Group"
      strength      = 100
      type          = bergsjaeger
      model         = 14
      extra         = engineer
      brigade_model = 0
    }
    division =
    { experience    = 15
      id            = { type = 22400 id = 94 }
      name          = "7th Special Operations Group"
      strength      = 100
      type          = bergsjaeger
      model         = 14
      extra         = engineer
      brigade_model = 0
    }
    division =
    { experience    = 15
      id            = { type = 22400 id = 95 }
      name          = "10th Special Operations Group"
      strength      = 100
      type          = bergsjaeger
      model         = 14
      extra         = engineer
      brigade_model = 0
    }
    division =
    { experience    = 15
      id            = { type = 22400 id = 96 }
      name          = "75th Ranger Regiment"
      strength      = 100
      type          = bergsjaeger
      model         = 14
      extra         = engineer
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 22400 id = 97 }
    location = 606
    name     = "National Guard Special Forces"
    division =
    { experience    = 5
      id            = { type = 22400 id = 98 }
      name          = "19th National Guard SO Group"
      strength      = 50
      type          = bergsjaeger
      model         = 13
      extra         = engineer
      brigade_model = 0
    }
    division =
    { experience    = 5
      id            = { type = 22400 id = 99 }
      name          = "20th National Guard SO Group"
      strength      = 50
      type          = bergsjaeger
      model         = 13
      extra         = engineer
      brigade_model = 0
    }
  }
  # #####################################
  # NAVY
  # ######################################
  navalunit =
  { id       = { type = 22400 id = 300 }
    location = 1184
    base     = 1184
    name     = "Kitty Hawk Strike Group"
    division =
    { id            = { type = 22400 id = 301 }
      name          = "USS Kitty Hawk  CV-63"
      type          = carrier
      model         = 0
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 302 }
      name  = "USS Chansellorsville  CG-62"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 303 }
      name  = "USS Cowpens  CG-63"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 304 }
      name  = "USS Vincennes  CG-49"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 305 }
      name  = "USS John S. McCain  DDG-56"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 306 }
      name  = "USS Cushing  DD-985"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 307 }
      name  = "USS O'Brien  DD-975"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 308 }
      name  = "USS Vandegrift  FFG-48"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 309 }
      name  = "USS Gary  FFG-51"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 310 }
      name  = "USS Curtis Wilbur  DDG-54"
      type  = light_cruiser
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 311 }
    location = 2041
    base     = 1614
    name     = "John F. Kennedy Strike Group"
    division =
    { id            = { type = 22400 id = 312 }
      name          = "USS John F. Kennedy  CV-67"
      type          = carrier
      model         = 0
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 313 }
      name  = "USS Vicksburg  CG-69"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 314 }
      name  = "USS Hue City  CG-66"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 315 }
      name  = "USS Monterey  CG-61"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 316 }
      name  = "USS Roosevelt  DDG-80"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 22400 id = 317 }
      name  = "USS Carney  DDG-64"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 318 }
      name  = "USS The Sullivans  DDG-68"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 319 }
      name  = "USS Spruance  DD-963"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 320 }
      name  = "USS O'Bannon  DD-987"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 321 }
      name  = "USS Underwood  FFG-36"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 322 }
      name  = "USS Estocin  FFG-15"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 323 }
      name  = "USS McInerney  FFG-8"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 324 }
      name  = "USS Doyle  FFG-39"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 325 }
      name  = "USS Klakring  FFG-42"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 326 }
      name  = "USS Robert G. Bradley  FFG-49"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 327 }
      name  = "USS Taylor  FFG-50"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 328 }
      name  = "USS Simpson  FFG-56"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 329 }
      name  = "USS Boone  FFG-28"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 330 }
    location = 633
    base     = 633
    name     = "Theodore Roosevelt Strike Group"
    division =
    { id            = { type = 22400 id = 331 }
      name          = "USS Theodore Roosevelt  CVN-71"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 332 }
      name  = "USS Cape St George  CG-71"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 333 }
      name  = "USS Anzio  CG-68"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 334 }
      name  = "USS Leyte Gulf  CG-55"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 335 }
      name  = "USS Vella Gulf  CG-72"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 336 }
      name  = "USS Winston S. Churchill  DDG-81"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 22400 id = 337 }
      name  = "USS Mitscher  DDG-57"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 338 }
      name  = "USS Porter  DDG-78"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 339 }
      name  = "USS Ramage  DDG-61"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 340 }
      name  = "USS Ross  DDG-71"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 341 }
      name  = "USS Hayler  DD-997"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 342 }
      name  = "USS Stump  DD-978"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 343 }
      name  = "USS Deyo  DD-989"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 344 }
      name  = "USS Halyburton  FFG-40"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 345 }
      name  = "USS Elrod  FFG-55"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 346 }
      name  = "USS Carr  FFG-52"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 347 }
      name  = "USS De Wert  FFG-45"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 348 }
    location = 633
    base     = 633
    name     = "Harry S. Truman Strike Group"
    division =
    { id            = { type = 22400 id = 349 }
      name          = "USS Harry S. Truman  (CVN-75)"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 350 }
      name  = "USS San Jacinto  CG-56"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 351 }
      name  = "USS Donald Cook  DDG-75"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 352 }
      name  = "USS Oscar Austin  DDG-79"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 22400 id = 353 }
      name  = "USS Cole  DDG-67"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 354 }
      name  = "USS Briscoe  DD-977"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 355 }
      name  = "USS Hawes  FFG-53"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 356 }
    location = 633
    base     = 633
    name     = "Enterprise Strike Group"
    division =
    { id            = { type = 22400 id = 357 }
      name          = "USS Enterprise  CVN-65"
      type          = carrier
      model         = 1
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 358 }
      name  = "USS Philippine Sea  CG-58"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 359 }
      name  = "USS Gettysburg  CG-64"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 360 }
      name  = "USS Stout  DDG-55"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 361 }
      name  = "USS Gonzalez  DDG-66"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 362 }
      name  = "USS McFaul  DDG-74"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 363 }
      name  = "USS Thorn  DD-988"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 364 }
      name  = "USS Nicholas  FFG-47"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 365 }
    location = 633
    base     = 633
    name     = "George Washington Strike Group"
    division =
    { id            = { type = 22400 id = 366 }
      name          = "USS George Washington  CVN-73"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 367 }
      name  = "USS Normandy  CG-60"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 368 }
      name  = "USS Mason  DDG-87"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 22400 id = 369 }
      name  = "USS Arleigh Burke  DDG-51"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 370 }
      name  = "USS Bulkeley  DDG-84"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 22400 id = 371 }
      name  = "USS Laboon  DDG-58"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 372 }
      name  = "USS Barry  DDG-52"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 373 }
      name  = "USS Mahan  DDG-72"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 374 }
      name  = "USS Kauffman  FFG-59"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 375 }
      name  = "USS Samuel B. Roberts  FFG-58"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 376 }
    location = 633
    base     = 633
    name     = "Dwight D. Eisenhower Strike Group"
    division =
    { id            = { type = 22400 id = 377 }
      name          = "USS Dwight D. Eisenhower  CVN-69"
      type          = carrier
      model         = 2
      strength      = 25
      extra         = cag
      brigade_model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 388 }
    location = 2041
    base     = 1614
    name     = "Amphibious Group Two"
    division =
    { id    = { type = 22400 id = 389 }
      name  = "USS Wasp  LHD-1"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 22400 id = 390 }
      name  = "USS Bataan  LHD-5"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 22400 id = 391 }
      name  = "USS Iwo Jima  LHD-7"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 22400 id = 392 }
      name  = "USS Kearsage  LHD-3"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 22400 id = 393 }
      name  = "USS Saipan  LHA-2"
      type  = transport
      model = 3
    }
    division =
    { id    = { type = 22400 id = 394 }
      name  = "USS Nassau  LHA-4"
      type  = transport
      model = 3
    }
    division =
    { id    = { type = 22400 id = 395 }
      name  = "Transport Fleet - Austin"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 396 }
      name  = "Transport Fleet - Shreveport"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 397 }
      name  = "Transport Fleet - Nashville"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 398 }
      name  = "Transport Fleet - Trenton"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 399 }
      name  = "Transport Fleet - Ponce"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 400 }
      name  = "Transport Fleet - San Antonio"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 401 }
      name  = "Transport Fleet - Whidbey Island"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 402 }
      name  = "Transport Fleet - Fort McHenry"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 403 }
      name  = "Transport Fleet - Ashland"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 404 }
      name  = "Transport Fleet - Carter Hall"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 405 }
      name  = "Transport Fleet - Oak Hill"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 406 }
      name  = "Transport Fleet - Mount Whitney"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { id       = { type = 22400 id = 407 }
    location = 780
    base     = 780
    name     = "Abraham Lincoln Strike Group"
    division =
    { id            = { type = 22400 id = 408 }
      name          = "USS Abraham Lincoln  CVN-72"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 409 }
      name  = "USS Shiloh  CG-67"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 410 }
      name  = "USS Bunker Hill  CG-52"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 411 }
      name  = "USS Shoup  DDG-86"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 22400 id = 412 }
      name  = "USS Preble  DDG-88"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 22400 id = 413 }
      name  = "USS Ford  FFG-54"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 414 }
      name  = "USS Ingraham  FFG-61"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 415 }
      name  = "USS Rodney M. Davis  FFG-60"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 416 }
    location = 761
    base     = 761
    name     = "Nimitz Strike Group"
    division =
    { id            = { type = 22400 id = 417 }
      name          = "USS Nimitz  CVN-68"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 418 }
      name  = "USS Mobile Bay  CG-53"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 419 }
      name  = "USS McCampbell  DDG-85"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 420 }
      name  = "USS Curts  FFG-38"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 421 }
    location = 761
    base     = 761
    name     = "Carl Vinson Strike Group"
    division =
    { id            = { type = 22400 id = 422 }
      name          = "USS Carl Vinson  CVN-70"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 423 }
      name  = "USS Antietam  CG-54"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 424 }
      name  = "USS Princeton  CG-59"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 425 }
      name  = "USS Lassen  DDG-82"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 22400 id = 426 }
      name  = "USS Frizgerald  DDG-62"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 427 }
      name  = "USS Decatur  DDG-73"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 428 }
      name  = "USS Oldendorf  DD-972"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 429 }
      name  = "USS Thach  FFG-43"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 430 }
    location = 761
    base     = 761
    name     = "Stennis Strike Group"
    division =
    { id            = { type = 22400 id = 431 }
      name          = "USS John C. Stennis  CVN-74"
      type          = carrier
      model         = 2
      extra         = cag
      brigade_model = 1
    }
    division =
    { id    = { type = 22400 id = 432 }
      name  = "USS Port Royal  CG-73"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 433 }
      name  = "USS Lake Champlain  CG-57"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 434 }
      name  = "USS Valley Forge  CG-50"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 435 }
      name  = "USS Stethem  DDG-63"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 436 }
      name  = "USS Higgins  DDG-76"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 437 }
      name  = "USS Elliot  DD-976"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 438 }
      name  = "USS Jarrett  FFG-33"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 439 }
      name  = "USS Rentz  FFG-46"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 440 }
    location = 761
    base     = 761
    name     = "Constellation Strike Group"
    division =
    { id            = { type = 22400 id = 441 }
      name          = "USS Constellation  CV-64"
      type          = carrier
      model         = 0
      extra         = cag
      brigade_model = 2
    }
    division =
    { id    = { type = 22400 id = 442 }
      name  = "USS Lake Erie  CG-70"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 443 }
      name  = "USS Chosin  CG-65"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 444 }
      name  = "USS Howard  DDG-83"
      type  = light_cruiser
      model = 3
    }
    division =
    { id    = { type = 22400 id = 445 }
      name  = "USS John Paul Jones  DDG-53"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 446 }
      name  = "USS Benford  DDG-65"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 447 }
      name  = "USS Milius  DDG-76"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 448 }
      name  = "USS McClusky  FFG-41"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 456 }
    location = 761
    base     = 761
    name     = "Amphibious Group Tree"
    division =
    { id    = { type = 22400 id = 457 }
      name  = "USS Boxer  LHD-4"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 22400 id = 458 }
      name  = "USS Bonhomme Richard  LHD-6"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 22400 id = 459 }
      name  = "USS Tarawa  LHA-1"
      type  = transport
      model = 3
    }
    division =
    { id    = { type = 22400 id = 460 }
      name  = "USS Belleau Wood  LHA-3"
      type  = transport
      model = 3
    }
    division =
    { id    = { type = 22400 id = 461 }
      name  = "USS Peleliu  LHA-5"
      type  = transport
      model = 3
    }
    division =
    { id    = { type = 22400 id = 462 }
      name  = "Transport Fleet - Comstock"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 463 }
      name  = "Transport Fleet - Rushmore"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 464 }
      name  = "Transport Fleet - Ogden"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 465 }
      name  = "Transport Fleet - Duluth"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 466 }
      name  = "Transport Fleet - Cleveland"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 467 }
      name  = "Transport Fleet - Denver"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 468 }
      name  = "Transport Fleet - Juneau"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { id       = { type = 22400 id = 469 }
    location = 1193
    base     = 1193
    name     = "Essex Amphibious Ready Group"
    division =
    { id    = { type = 22400 id = 470 }
      name  = "USS Essex  LHD-2"
      type  = transport
      model = 4
    }
    division =
    { id    = { type = 22400 id = 471 }
      name  = "Transport Fleet - Anchorage"
      type  = transport
      model = 0
    }
    division =
    { id    = { type = 22400 id = 472 }
      name  = "Transport Fleet - Mount Vernon"
      type  = transport
      model = 0
    }
  }
  navalunit =
  { id       = { type = 22400 id = 473 }
    location = 1193
    base     = 1193
    name     = "Destroyer Squadron Six"
    division =
    { id    = { type = 22400 id = 474 }
      name  = "USS Ticonderoga  CG-47"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 475 }
      name  = "USS Yorktown  CG-48"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 476 }
      name  = "USS Thomas S. Gates  CG-51"
      type  = battlecruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 477 }
      name  = "USS Stephen W. Groves  FFG-29"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 478 }
      name  = "USS John L. Hall  FFG-32"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 479 }
    location = 663
    base     = 663
    name     = "Destroyer Squadron Thirty-One"
    division =
    { id    = { type = 22400 id = 480 }
      name  = "USS Russel  DDG-59"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 481 }
      name  = "USS Paul Hamilton  DDG-60"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 482 }
      name  = "USS Hopper  DDG-70"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 483 }
      name  = "USS O'Kane  DDG-77"
      type  = light_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 484 }
      name  = "USS Fletcher  DD-992"
      type  = light_cruiser
      model = 1
    }
    division =
    { id    = { type = 22400 id = 485 }
      name  = "USS Crommelin  FFG-37"
      type  = destroyer
      model = 2
    }
    division =
    { id    = { type = 22400 id = 486 }
      name  = "USS Reuben James  FFG-57"
      type  = destroyer
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 487 }
    location = 663
    base     = 663
    name     = "Submarine Squadron One"
    division =
    { id    = { type = 22400 id = 488 }
      name  = "USS Los Angeles  SSN-688"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 489 }
      name  = "USS La Jolla  SSN-701"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 490 }
      name  = "USS San Francisco  SSN-711"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 491 }
      name  = "USS Buffalo  SSN-715"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 492 }
      name  = "USS Charlotte SSN-766"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 493 }
      name  = "USS Greeneville  SSN-772"
      type  = submarine
      model = 15
    }
  }
  navalunit =
  { id       = { type = 22400 id = 494 }
    location = 663
    base     = 663
    name     = "Submarine Squadron Three"
    division =
    { id    = { type = 22400 id = 495 }
      name  = "USS Olympia  SSN-717"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 496 }
      name  = "USS Honolulu  SSN-718"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 497 }
      name  = "USS Chicago  SSN-721"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 498 }
      name  = "USS Key West  SSN-722"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 499 }
      name  = "USS Louisville SSN-724"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 500 }
      name  = "USS Asheville  SSN-758"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 501 }
      name  = "USS Columbia  SSN-771"
      type  = submarine
      model = 15
    }
  }
  navalunit =
  { id       = { type = 22400 id = 502 }
    location = 663
    base     = 663
    name     = "Submarine Squadron Seven"
    division =
    { id    = { type = 22400 id = 503 }
      name  = "USS Pasadena  SSN-752"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 504 }
      name  = "USS Topeka  SSN-754"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 505 }
      name  = "USS Columbus  SSN-762"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 506 }
      name  = "USS Santa Fe  SSN-763"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 507 }
      name  = "USS Cheyenne SSN-773"
      type  = submarine
      model = 15
    }
  }
  navalunit =
  { id       = { type = 22400 id = 508 }
    location = 1624
    base     = 1624
    name     = "Submarine Squadron Fifteen"
    division =
    { id    = { type = 22400 id = 509 }
      name  = "USS City of Corpus Christi  SSN-705"
      type  = submarine
      model = 14
    }
  }
  navalunit =
  { id       = { type = 22400 id = 510 }
    location = 600
    base     = 600
    name     = "Submarine Squadron Two"
    division =
    { id    = { type = 22400 id = 511 }
      name  = "USS Dallas  SSN-700"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 512 }
      name  = "USS Alberquerque  SSN-706"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 513 }
      name  = "USS Pittsburgh  SSN-720"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 514 }
      name  = "USS Springfield  SSN-761"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 515 }
      name  = "USS Toledo  SSN-769"
      type  = submarine
      model = 15
    }
  }
  navalunit =
  { id       = { type = 22400 id = 516 }
    location = 600
    base     = 600
    name     = "Submarine Squadron Four"
    division =
    { id    = { type = 22400 id = 517 }
      name  = "USS Providence  SSN-719"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 518 }
      name  = "USS Miami  SSN-755"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 519 }
      name  = "USS Annapolis  SSN-760"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 520 }
      name  = "USS Hartford  SSN-768"
      type  = submarine
      model = 15
    }
  }
  navalunit =
  { id       = { type = 22400 id = 521 }
    location = 600
    base     = 600
    name     = "Submarine Squadron Eigth"
    division =
    { id    = { type = 22400 id = 522 }
      name  = "USS Oklahoma City  SSN-723"
      type  = submarine
      model = 14
    }
  }
  navalunit =
  { id       = { type = 22400 id = 523 }
    location = 600
    base     = 600
    name     = "Submarine Development Squadron Twelve"
    division =
    { id    = { type = 22400 id = 524 }
      name  = "USS Philadelphia  SSN-690"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 525 }
      name  = "USS Augusta  SSN-610"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 526 }
      name  = "USS San Juan  SSN-751"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 527 }
      name  = "USS Alexandria  SSN-757"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 528 }
      name  = "USS Memphis  SSN-691"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 529 }
      name  = "USS Seawolf  SSN-21"
      type  = submarine
      model = 16
    }
    division =
    { id    = { type = 22400 id = 530 }
      name  = "USS Connecticut  SSN-22"
      type  = submarine
      model = 16
    }
  }
  navalunit =
  { id       = { type = 22400 id = 449 }
    location = 761
    base     = 761
    name     = "Submarine Squadron Eleven"
    division =
    { id    = { type = 22400 id = 450 }
      name  = "USS Bremerton  SSN-698"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 451 }
      name  = "USS Portsmouth  SSN-707"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 452 }
      name  = "USS Houston  SSN-713"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 453 }
      name  = "USS Salt Lake City  SSN-716"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 454 }
      name  = "USS Helena  SSN-725"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 455 }
      name  = "USS Jefferson City  SSN-759"
      type  = submarine
      model = 15
    }
  }
  navalunit =
  { id       = { type = 22400 id = 378 }
    location = 633
    base     = 633
    name     = "Submarine Squadron Six"
    division =
    { id    = { type = 22400 id = 379 }
      name  = "USS Montpelier  SSN-765"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 380 }
      name  = "USS Norfolk  SSN-714"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 381 }
      name  = "USS Minneapolis-Saint Paul  SSN-708"
      type  = submarine
      model = 14
    }
  }
  navalunit =
  { id       = { type = 22400 id = 382 }
    location = 633
    base     = 633
    name     = "Submarine Squadron Eight"
    division =
    { id    = { type = 22400 id = 383 }
      name  = "USS Jacksonville  SSN-699"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 384 }
      name  = "USS Hyman G. Rickover  SSN-709"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 385 }
      name  = "USS Newport News  SSN-750"
      type  = submarine
      model = 14
    }
    division =
    { id    = { type = 22400 id = 386 }
      name  = "USS Boise  SSN-764"
      type  = submarine
      model = 15
    }
    division =
    { id    = { type = 22400 id = 387 }
      name  = "USS Hampton  SSN-767"
      type  = submarine
      model = 15
    }
  }
  navalunit =
  { id       = { type = 22400 id = 531 }
    location = 600
    base     = 600
    name     = "Groton SSGN Command"
    division =
    { id    = { type = 22400 id = 532 }
      name  = "USS Ohio  SSGN-726"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 533 }
      name  = "USS Florida  SSGN-728"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 534 }
      name  = "USS Henry M. Jackson  SSGN-730"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 535 }
      name  = "USS Alabama  SSGN-731"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 536 }
      name  = "USS Nevada  SSGN-733"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 537 }
      name  = "USS Pennsylvania  SSGN-735"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 538 }
      name  = "USS Kentucky  SSGN-737"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 539 }
      name  = "USS Nebraska  SSGN-739"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 540 }
      name  = "USS Maine  SSGN-741"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 541 }
      name  = "USS Louisiana  SSGN-743"
      type  = heavy_cruiser
      model = 2
    }
  }
  navalunit =
  { id       = { type = 22400 id = 542 }
    location = 648
    base     = 648
    name     = "Submarine Group Ten"
    division =
    { id    = { type = 22400 id = 543 }
      name  = "USS Michigan  SSGN-727"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 544 }
      name  = "USS Georgia  SSGN-729"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 545 }
      name  = "USS Alaska  SSGN-732"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 546 }
      name  = "USS Tennessee  SSGN-734"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 547 }
      name  = "USS West Virginia  SSGN-736"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 548 }
      name  = "USS Maryland  SSGN-738"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 549 }
      name  = "USS Rhode Island  SSGN-740"
      type  = heavy_cruiser
      model = 2
    }
    division =
    { id    = { type = 22400 id = 550 }
      name  = "USS Wyoming  SSGN-742"
      type  = heavy_cruiser
      model = 2
    }
  }
  # #####################################
  # AIR FORCE
  # #####################################
  airunit =
  { id       = { type = 22400 id = 100 }
    location = 621
    base     = 621
    name     = "2nd Bomb Wing"
    division =
    { id       = { type = 22400 id = 101 }
      name     = "11th Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 102 }
      name     = "20th Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 103 }
      name     = "96th Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 0
    }
  }
  airunit =
  { id       = { type = 22400 id = 104 }
    location = 621
    base     = 621
    name     = "5th Bomb Wing"
    division =
    { id       = { type = 22400 id = 105 }
      name     = "23rd Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 0
    }
  }
  airunit =
  { id       = { type = 22400 id = 106 }
    location = 1614
    base     = 1614
    name     = "509th Bomb Wing"
    division =
    { id       = { type = 22400 id = 107 }
      name     = "13th Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 5
    }
    division =
    { id       = { type = 22400 id = 108 }
      name     = "393rd Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 5
    }
  }
  airunit =
  { id       = { type = 22400 id = 109 }
    location = 1614
    base     = 1614
    name     = "7th Bomb Wing"
    division =
    { id       = { type = 22400 id = 110 }
      name     = "9th Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 2
    }
    division =
    { id       = { type = 22400 id = 111 }
      name     = "28th Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 2
    }
    division =
    { id       = { type = 22400 id = 112 }
      name     = "14th Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 2
    }
  }
  airunit =
  { id       = { type = 22400 id = 113 }
    location = 621
    base     = 621
    name     = "28th Bomb Wing"
    division =
    { id       = { type = 22400 id = 114 }
      name     = "34th Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 2
    }
    division =
    { id       = { type = 22400 id = 115 }
      name     = "37th Bomb Squadron"
      type     = strategic_bomber
      strength = 100
      model    = 2
    }
  }
  airunit =
  { id       = { type = 22400 id = 116 }
    location = 1614
    base     = 1614
    name     = "1st Fighter Wing"
    division =
    { id       = { type = 22400 id = 117 }
      name     = "27th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 118 }
      name     = "71st Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 119 }
      name     = "94th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 120 }
    location = 1614
    base     = 1614
    name     = "4th Fighter Wing"
    division =
    { id       = { type = 22400 id = 121 }
      name     = "335th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 122 }
      name     = "336th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 123 }
    location = 1614
    base     = 1614
    name     = "20th Fighter Wing"
    division =
    { id       = { type = 22400 id = 124 }
      name     = "55th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 125 }
      name     = "77th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 126 }
      name     = "79th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 127 }
    location = 651
    base     = 651
    name     = "33rd Fighter Wing"
    division =
    { id       = { type = 22400 id = 128 }
      name     = "57th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 129 }
      name     = "60th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 130 }
    location = 651
    base     = 651
    name     = "23rd Fighter Group"
    division =
    { id       = { type = 22400 id = 131 }
      name     = "59th Fighter Squadron"
      type     = cas
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 132 }
      name     = "58th Fighter Squadron"
      type     = cas
      strength = 100
      model    = 0
    }
  }
  airunit =
  { id       = { type = 22400 id = 133 }
    location = 1614
    base     = 1614
    name     = "49th Fighter Wing"
    division =
    { id       = { type = 22400 id = 134 }
      name     = "8th Fighter Squadron"
      type     = tactical_bomber
      strength = 100
      model    = 6
    }
    division =
    { id       = { type = 22400 id = 135 }
      name     = "9th Fighter Squadron"
      type     = tactical_bomber
      strength = 100
      model    = 6
    }
  }
  airunit =
  { id       = { type = 22400 id = 136 }
    location = 766
    base     = 766
    name     = "27th Fighter Wing"
    division =
    { id       = { type = 22400 id = 137 }
      name     = "522nd Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 138 }
      name     = "523rd Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 139 }
      name     = "524th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 140 }
      name     = "428th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 141 }
    location = 1614
    base     = 1614
    name     = "355th Wing"
    division =
    { id       = { type = 22400 id = 142 }
      name     = "354th Fighter Squadron"
      type     = cas
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 143 }
      name     = "357th Fighter Squadron"
      type     = cas
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 144 }
      name     = "358th Fighter Squadron"
      type     = cas
      strength = 100
      model    = 0
    }
  }
  airunit =
  { id       = { type = 22400 id = 145 }
    location = 1614
    base     = 1614
    name     = "366th Expeditionary Wing"
    division =
    { id       = { type = 22400 id = 146 }
      name     = "389th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 147 }
      name     = "390th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 148 }
      name     = "391st Fighter Squadron"
      type     = tactical_bomber
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 149 }
    location = 1614
    base     = 1614
    name     = "388th Fighter Wing"
    division =
    { id       = { type = 22400 id = 150 }
      name     = "4th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 151 }
      name     = "34th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 152 }
      name     = "421st Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 153 }
    location = 766
    base     = 766
    name     = "301st Fighter Wing"
    division =
    { id       = { type = 22400 id = 154 }
      name     = "457th Fighter Squadron"
      type     = interceptor
      strength = 30
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 155 }
    location = 766
    base     = 766
    name     = "419th Fighter Wing"
    division =
    { id       = { type = 22400 id = 156 }
      name     = "466th Fighter Squadron"
      type     = interceptor
      strength = 30
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 157 }
    location = 766
    base     = 766
    name     = "442nd Fighter Wing"
    division =
    { id       = { type = 22400 id = 158 }
      name     = "303rd Fighter Squadron"
      type     = cas
      strength = 30
      model    = 0
    }
  }
  airunit =
  { id       = { type = 22400 id = 159 }
    location = 651
    base     = 651
    name     = "482nd Fighter Wing"
    division =
    { id       = { type = 22400 id = 160 }
      name     = "93rd Fighter Squadron"
      type     = interceptor
      strength = 30
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 161 }
    location = 651
    base     = 651
    name     = "926th Fighter Wing"
    division =
    { id       = { type = 22400 id = 162 }
      name     = "706th Fighter Squadron"
      type     = cas
      strength = 30
      model    = 0
    }
  }
  airunit =
  { id       = { type = 22400 id = 163 }
    location = 722
    base     = 722
    name     = "944th Fighter Wing"
    division =
    { id       = { type = 22400 id = 164 }
      name     = "301st Fighter Squadron"
      type     = interceptor
      strength = 30
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 165 }
      name     = "302nd Fighter Squadron"
      type     = interceptor
      strength = 30
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 166 }
    location = 722
    base     = 722
    name     = "917th Fighter Wing"
    division =
    { id       = { type = 22400 id = 167 }
      name     = "47th Fighter Squadron"
      type     = cas
      strength = 30
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 168 }
      name     = "93rd Bomb Squadron"
      type     = strategic_bomber
      strength = 30
      model    = 0
    }
  }
  airunit =
  { id       = { type = 22400 id = 169 }
    location = 595
    base     = 595
    name     = "103rd Fighter Wing"
    division =
    { id       = { type = 22400 id = 170 }
      name     = "118th Fighter Squadron"
      type     = cas
      strength = 70
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 171 }
      name     = "131st Fighter Squadron"
      type     = cas
      strength = 70
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 172 }
      name     = "172nd Fighter Squadron"
      type     = cas
      strength = 70
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 173 }
      name     = "103rd Fighter Squadron"
      type     = cas
      strength = 70
      model    = 0
    }
  }
  airunit =
  { id       = { type = 22400 id = 174 }
    location = 621
    base     = 621
    name     = "131st Fighter Wing"
    division =
    { id       = { type = 22400 id = 175 }
      name     = "110th Fighter Squadron"
      type     = multi_role
      strength = 70
      model    = 2
    }
    division =
    { id       = { type = 22400 id = 176 }
      name     = "122nd Fighter Squadron"
      type     = multi_role
      strength = 70
      model    = 2
    }
  }

  airunit =
  { id       = { type = 22400 id = 177 }
    location = 766
    base     = 766
    name     = "114th Fighter Wing"
    division =
    { id       = { type = 22400 id = 178 }
      name     = "175th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 179 }
      name     = "163rd Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 180 }
      name     = "115th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 2
    }
  }

  airunit =
  { id       = { type = 22400 id = 181 }
    location = 722
    base     = 722
    name     = "132nd Fighter Wing"
    division =
    { id       = { type = 22400 id = 182 }
      name     = "124th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 183 }
      name     = "125th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 184 }
      name     = "188th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 185 }
      name     = "157th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 186 }
    location = 595
    base     = 595
    name     = "174th Fighter Wing"
    division =
    { id       = { type = 22400 id = 187 }
      name     = "138th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 188 }
      name     = "119th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 189 }
      name     = "112nd Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 190 }
      name     = "170th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 191 }
    location = 651
    base     = 651
    name     = "185st Fighter Wing"
    division =
    { id       = { type = 22400 id = 192 }
      name     = "174th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 193 }
      name     = "160th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 194 }
      name     = "184th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 195 }
      name     = "149th Fighter Squadron"
      type     = interceptor
      strength = 70
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 196 }
    location = 1614
    base     = 1614
    name     = "3rd Wing"
    division =
    { id       = { type = 22400 id = 197 }
      name     = "12th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 198 }
      name     = "19th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 199 }
      name     = "90th Fighter Squadron"
      type     = tactical_bomber
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 200 }
    location = 663
    base     = 663
    name     = "354th Fighter Wing"
    division =
    { id       = { type = 22400 id = 201 }
      name     = "355th Fighter Squadron"
      type     = cas
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 202 }
      name     = "18th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 203 }
    location = 1614
    base     = 1614
    name     = "48th Fighter Wing"
    division =
    { id       = { type = 22400 id = 204 }
      name     = "492nd Fighter Squadron"
      type     = tactical_bomber
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 205 }
      name     = "493rd Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 206 }
      name     = "494th Fighter Squadron"
      type     = tactical_bomber
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 207 }
    location = 1614
    base     = 1614
    name     = "48th Fighter Wing"
    division =
    { id       = { type = 22400 id = 208 }
      name     = "22nd Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 209 }
      name     = "23rd Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 210 }
      name     = "81st Fighter Squadron"
      type     = cas
      strength = 100
      model    = 0
    }
  }
  airunit =
  { id       = { type = 22400 id = 211 }
    location = 370
    base     = 370
    name     = "31st Fighter Wing"
    division =
    { id       = { type = 22400 id = 212 }
      name     = "510th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 213 }
      name     = "555th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 214 }
    location = 1614
    base     = 1614
    name     = "18th Wing"
    division =
    { id       = { type = 22400 id = 215 }
      name     = "44th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 216 }
      name     = "67th Fighter Squadron"
      type     = multi_role
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 217 }
    location = 1614
    base     = 1614
    name     = "35th Fighter Wing"
    division =
    { id       = { type = 22400 id = 228 }
      name     = "13th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 229 }
      name     = "14th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 230 }
    location = 1614
    base     = 1614
    name     = "8th Fighter Wing"
    division =
    { id       = { type = 22400 id = 231 }
      name     = "35th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
    division =
    { id       = { type = 22400 id = 232 }
      name     = "80th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 233 }
    location = 1614
    base     = 1614
    name     = "51st Fighter Wing"
    division =
    { id       = { type = 22400 id = 234 }
      name     = "25th Fighter Squadron"
      type     = cas
      strength = 100
      model    = 0
    }
    division =
    { id       = { type = 22400 id = 235 }
      name     = "36th Fighter Squadron"
      type     = interceptor
      strength = 100
      model    = 3
    }
  }
  airunit =
  { id       = { type = 22400 id = 236 }
    location = 1614
    base     = 1614
    name     = "3rd Air Force"
    division =
    { id       = { type = 22400 id = 237 }
      name     = "86th Airlift Wing"
      type     = transport_plane
      strength = 100
      model    = 1
    }
    division =
    { id       = { type = 22400 id = 238 }
      name     = "374th Airlift Wing"
      type     = transport_plane
      strength = 100
      model    = 1
    }
  }
  airunit =
  { id       = { type = 22400 id = 239 }
    location = 1614
    base     = 1614
    name     = "11th Air Force"
    division =
    { id       = { type = 22400 id = 240 }
      name     = "176th Wing"
      type     = transport_plane
      strength = 100
      model    = 1
    }
  }
  airunit =
  { id       = { type = 22400 id = 241 }
    location = 1614
    base     = 1614
    name     = "13th Air Force"
    division =
    { id       = { type = 22400 id = 242 }
      name     = "15th Air Base Wing"
      type     = transport_plane
      strength = 100
      model    = 0
    }
  }
  # ###################################
  # Under Development
  # ###################################
  division_development =
  { id    = { type = 22400 id = 600 }
    name  = "USS Ronald Reagan  CVN-76"
    type  = carrier
    model = 2
    cost  = 15
      extra         = cag
      brigade_model = 2
    date  = { day = 10 month = october year = 2003 }
  }
  division_development =
  { id    = { type = 22400 id = 601 }
    name  = "USS Momsen  DDG-92"
    type  = light_cruiser
    model = 3
    cost  = 5
    date  = { day = 17 month = march year = 2004 }
  }
  division_development =
  { id    = { type = 22400 id = 602 }
    name  = "USS Virginia  SSN-774"
    type  = submarine
    model = 16
    cost  = 5
    date  = { day = 1 month = may year = 2004 }
  }
  division_development =
  { id    = { type = 22400 id = 603 }
    name  = "USS Chung-Hoon  DDG-93"
    type  = light_cruiser
    model = 3
    cost  = 5
    date  = { day = 13 month = september year = 2004 }
  }
  division_development =
  { id    = { type = 22400 id = 604 }
    name  = "USS Nitze  DDG-94"
    type  = light_cruiser
    model = 3
    cost  = 5
    date  = { day = 12 month = january year = 2005 }
  }
  division_development =
  { id    = { type = 22400 id = 605 }
    name  = "USS James E. Williams  DDG-95"
    type  = light_cruiser
    model = 3
    cost  = 5
    date  = { day = 22 month = april year = 2005 }
  }
  division_development =
  { id    = { type = 22400 id = 606 }
    name  = "USS Bainbridge  DDG-96"
    type  = light_cruiser
    model = 3
    cost  = 5
    date  = { day = 20 month = august year = 2005 }
  }
  division_development =
  { id    = { type = 22400 id = 607 }
    name  = "USS Halsey  DDG-97"
    type  = light_cruiser
    model = 3
    cost  = 5
    date  = { day = 4 month = november year = 2005 }
  }
  division_development =
  { id    = { type = 22400 id = 608 }
    name  = "USS Texas  SSN-775"
    type  = submarine
    model = 16
    cost  = 5
    date  = { day = 8 month = june year = 2005 }
  }
  division_development =
  { id    = { type = 22400 id = 611 }
    name  = "USS Forrest Sherman  DDG-98"
    type  = light_cruiser
    model = 3
    cost  = 5
    date  = { day = 21 month = february year = 2006 }
  }
  division_development =
  { id    = { type = 22400 id = 612 }
    name  = "USS Farragut  DDG-99"
    type  = light_cruiser
    model = 3
    cost  = 5
    date  = { day = 2 month = july year = 2006 }
  }
  division_development =
  { id    = { type = 22400 id = 613 }
    name  = "USS Mesa Verde  LPD-19"
    type  = transport
    model = 4
    cost  = 10
    date  = { day = 26 month = may year = 2006 }
  }
  division_development =
  { id    = { type = 22400 id = 614 }
    name  = "USS Trent Lott  LPD-20"
    type  = transport
    model = 4
    cost  = 10
    date  = { day = 9 month = october year = 2006 }
  }
  division_development =
  { id    = { type = 22400 id = 615 }
    name  = "USS Hawaii  SSN-776"
    type  = submarine
    model = 16
    cost  = 5
    date  = { day = 25 month = may year = 2007 }
  }
  division_development =
  { id    = { type = 22400 id = 616 }
    name  = "USS George H. W. Bush  CVN-77"
    type  = carrier
    model = 2
    cost  = 40
      extra         = cag
      brigade_model = 2
    date  = { day = 3 month = august year = 2008 }
  }
  division_development =
  { id    = { type = 22400 id = 617 }
    name  = "USS North Carolina  SSN-777"
    type  = submarine
    model = 16
    cost  = 5
    date  = { day = 17 month = june year = 2008 }
  }
}